<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\TransactionHistory;

/**
 * TransactionHistoryRepository class
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionHistoryRepository extends EntityRepository
{
    /**
     * @param $referenceId
     * @return TransactionHistory|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getCurrentStatusByReferenceId($referenceId)
    {
        $queryBuilder = $this->createQueryBuilder('th')
            ->select('th')
            ->where('th.referenceId=:referenceId')
            ->setParameter('referenceId', $referenceId)
            ->orderBy('th.createdAt', 'DESC')
            ->setMaxResults(1);

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
