services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Service\StorageService:
        arguments:
            - Predis\Client
        public: false

    AppBundle\Service\OrderProducer:
        arguments:
            - Mullenlowe\CommonBundle\Component\AMQP\CrudProducer
        public: false
