PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE pay_transaction (id INTEGER NOT NULL, reference_id VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, currency VARCHAR(10) NOT NULL, created_at DATETIME NOT NULL, origin VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE TABLE pay_transaction_history (id INTEGER NOT NULL, reference_id VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id));
COMMIT;
